# Copyright (c) 2025 Philipp Miedl
#
# SPDX-License-Identifier: EUPL-1.2

name: stechuhr
description: "A simple time recording app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_analog_clock: ^1.0.3
  scaled_app: ^2.3.0
  duration_picker: ^1.2.0
  date_field: ^6.0.3+1
  intl: ^0.20.2
  flutter_overlay: ^1.0.0
  rust_lib_stechuhr:
    path: rust_builder
  flutter_rust_bridge: 2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true